name = "NTECARS"
uuid = "276900cb-bc55-4057-85e0-0ed4429d725b"
version = "1.0.0-DEV"
authors = ["Christian Busch <88284600+ChristianABusch@users.noreply.github.com> and contributors"]

[workspace]
projects = ["docs"]

[deps]
ADTypes = "47edcb42-4c32-4615-8424-f2b9edc5f35b"
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
DSP = "717857b8-e6f2-59f4-9121-6e50c889abd2"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Dierckx = "39dd38d3-220a-591b-8e3c-4c3a8c710a94"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
DocumenterTools = "35a29f4d-8980-5a13-9543-d66fff28ecb8"
FiniteDiff = "6a86dc24-6348-571c-b903-95158fe2bd41"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
Ipopt = "b6b21f68-93f8-5de0-b562-5493be1d77c9"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LiveServer = "16fef848-5104-11e9-1b77-fb7a48bbb589"
LoopVectorization = "bdcacae8-1622-11e9-2a5c-532679323890"
Measurements = "eff96d63-e80a-5855-80a2-b1b0885c5ab7"
NonlinearSolve = "8913a72c-1f9b-4ce2-8d82-65094dcecaec"
Optimization = "7f7a1694-90dd-40f0-9382-eb1efda571ba"
OptimizationBase = "bca83a33-5cc9-4baa-983d-23429ab6bcbb"
OptimizationIpopt = "43fad042-7963-4b32-ab19-e2a4f9a67124"
OptimizationMOI = "fd9f6733-72f4-499f-8506-86b2bdd0dea1"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
PhysicalConstants = "5ad8b20f-a522-5ce9-bfc9-ddf1d5bda6ab"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
Roots = "f2b01f46-fcfa-551c-844a-d8ac1e96c665"
SciMLBase = "0bca4576-84f4-4d90-8ffe-ffa030f20462"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
TOML = "fa267f1f-6049-4f14-aa54-33bafae1ed76"
UnPack = "3a884ed6-31ef-47d7-9d2a-63182c4928ed"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"

[compat]
ADTypes = "1.21.0"
BenchmarkTools = "1.6.3"
CSV = "0.10.15"
CairoMakie = "0.15.8"
DSP = "0.8.4"
DataFrames = "1.8.1"
Dierckx = "0.5.4"
Documenter = "1.16.1"
DocumenterTools = "0.1.21"
FiniteDiff = "2.29.0"
ForwardDiff = "1.3.1"
Interpolations = "0.16.2"
Ipopt = "1.13.0"
LinearAlgebra = "1.12.0"
LiveServer = "1.5.0"
LoopVectorization = "0.12.173"
Measurements = "2.14.1"
NonlinearSolve = "4.14.0"
Optimization = "5.3.0"
OptimizationBase = "4.0.2"
OptimizationIpopt = "1.0.0"
OptimizationMOI = "1.0.0"
Parameters = "0.12.3"
PhysicalConstants = "0.2.4"
Revise = "3.13.2"
Roots = "2.2.10"
SciMLBase = "2.131.0"
SpecialFunctions = "2.6.1"
StaticArrays = "1.9.15"
Statistics = "1.11.1"
TOML = "1.0.3"
UnPack = "1.0.2"
Unitful = "1.27.0"
julia = "1.12"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
